package com.myspace;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InfoPaciente implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("documento")
	private java.lang.Integer documento;
	@org.kie.api.definition.type.Label("Nombre completo")
	private java.lang.String nombre;
	private java.lang.Long id;
	@org.kie.api.definition.type.Label("Fecha de nacimiento")
	private java.time.LocalDate fechaNacimiento;

	public InfoPaciente() {
	}

	public java.lang.Integer getDocumento() {
		return this.documento;
	}

	public void setDocumento(java.lang.Integer documento) {
		this.documento = documento;
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.time.LocalDate getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(java.time.LocalDate fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public InfoPaciente(java.lang.Integer documento, java.lang.String nombre,
			java.lang.Long id, java.time.LocalDate fechaNacimiento) {
		this.documento = documento;
		this.nombre = nombre;
		this.id = id;
		this.fechaNacimiento = fechaNacimiento;
	}

}